frutas = ('laranja', 'banana', 'maça', 'uva', 'goiaba')
indice_laranja = frutas.index('laranja')
print('Indice da laranja', indice_laranja)

qtd_banana = frutas.count('banana')
print('Quantidade de bananas', qtd_banana)
print('Fruta 1',)
print('Fruta 1',)
print('Fruta 1',)
print('Fruta 1',)
print('Fruta 1',)